// import './js/phones.js'
import './scss/style.scss'
import './js/images.js'
import './js/header.js'
import './js/utils.js'
import './js/casesMain.js'
import './js/casesCases.js'
import './js/uspSlider.js'
import './js/partnerSlider.js'
